//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Model.Campaign;
using ArabyAds.AdFalcon.Domain.Model.Campaign.Targeting;
using ArabyAds.AdFalcon.Domain.Model.AppSite;
using ArabyAds.AdFalcon.Domain.Model.Core;
using ArabyAds.Framework.DomainServices;
using ArabyAds.AdFalcon.Domain.Common.Model.Campaign;

namespace ArabyAds.AdFalcon.Domain.Model.Campaign
{
    //[DataContract()]
    //public enum HouseAdDeliveryMode
    //{
    //    [EnumMember]
    //    [EnumText("WhenNoAds", "HouseAd")]
    //    WhenNoAds = 1,
    //    [EnumMember]
    //    [EnumText("FullyAllocate", "HouseAd")]
    //    FullyAllocate = 2
    //}
    public class HouseAd : IEntity<int>
    {
        public HouseAd(AdGroup adGroup)
        {
            AdGroup = adGroup;
            AdGroupId = adGroup.ID;
            DestinationAppSites = new List<AppSite.AppSite>();
        }
        public HouseAd()
        {
            DestinationAppSites = new List<AppSite.AppSite>();
        }
        public virtual int ID { get;  set; }
        public virtual bool IsDeleted { get; set; }
        public virtual HouseAdDeliveryMode DeliveryMode { get; set; }

        public virtual Account.Account Account { get; set; }

        public virtual Account.User User { get; set; }
        public virtual AppSite.AppSite ForAppSite { get; set; }
        public virtual IEnumerable<AppSite.AppSite> DestinationAppSites { get; set; }

        public virtual AdGroup AdGroup { get; set; }
        private int AdGroupId { get; set; }

        public virtual void AddDestinationAppSite(AppSite.AppSite appsite)
        {
            (DestinationAppSites as ICollection<AppSite.AppSite>).Add(appsite);
        }
        public virtual void ClearDestinationAppSite()
        {
            DestinationAppSites = new List<AppSite.AppSite>();
        }
        public virtual void Delete()
        {
            AdGroup.Delete();
            IsDeleted = true;
        }

        public virtual void Pause()
        {
            AdGroup.Pause();
        }
        public virtual void Resume()
        {
            AdGroup.Resume();
        }

        public virtual HouseAd Clone()
        {
            var cloneObj = new HouseAd()
            {
                DeliveryMode = this.DeliveryMode,
                Account = this.Account,
                User = this.User,
                ForAppSite = this.ForAppSite,
                DestinationAppSites = new List<AppSite.AppSite>(),
            };
            foreach (var destinationAppSite in DestinationAppSites)
            {
                ((List<AppSite.AppSite>)cloneObj.DestinationAppSites).Add(destinationAppSite);
            }
            return cloneObj;
        }
        public virtual string GetDescription()
        {
            return /*"House Ad for " + */ForAppSite.GetDescription();
        }

    }
}

