//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.Campaign
{
    public class TileImageSize : LookupBase<TileImageSize, int>
    {
        public virtual int Width { get; set; }
        public virtual int Height { get; set; }
        public virtual Core.DeviceType DeviceType { get; set; }
        public virtual bool IsActionTile { get; set; }
        public virtual TileImageSize TitleSize { get; set; }
        public virtual IList<TileImageFormat> Formats { get; set; }
        public override string ToString()
        {
            return string.Format("{0}X{1}", Width, Height);
        }
    }
}

