//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using Noqoush.AdFalcon.Domain.Common.Model.Account;
using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Account
{
    //public enum FeaturesCode
    //{
    //    PopOver = 1,
    //}

    public class Feature : ManagedLookupBase
    {
        public virtual FeaturesCode Code { set; get; }
    }
}

