//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Noqoush.Framework.DomainServices;

namespace Noqoush.AdFalcon.Domain.Model.Account
{
    //Osaleh :- remove this class becuse it same as AccountFundTransHistory
//    public class Fund : IEntity<int>
//    {
//        public virtual bool IsDeleted { get; set; }
//        public virtual DateTime FundDate
//        {
//            get;
//            set;
//        }

//        public virtual string Currency 
//        { 
//            get; 
//            set;
//        }

//        public virtual string Payee 
//        { 
//            get;
//            set; 
//        }

//        public virtual string TransactionId
//        {
//            get;
//            set;
//        }

//        public virtual decimal Amount
//        {
//            get;
//            set;
//        }

//        public virtual FundType Type
//        {
//            get;
//            set;
//        }

//        public virtual User User
//        {
//            get;
//            set;
//        }

//        public virtual Account Account
//        {
//            get;
//            set;
//        }



//        public virtual int ID { get; set; }
//    }
}

