//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Account
{
    public class UserStatus : LookupBase<UserStatus,int>
    {
        public const int PendingUser = 1;
        public const int ActiveUser = 2;
        public const int DeletedUser = 3;

        public virtual void SetActiveStatus()
        {
            ID = ActiveUser;
        }

        public virtual void SetPendingStatus()
        {
            ID = PendingUser;
        }

        public virtual void SetDeletingStatus()
        {
            ID = DeletedUser;
        }
    }
}

