//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Common.Model.AppSite;
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.Framework.DomainServices;
using System;

namespace Noqoush.AdFalcon.Domain.Model.AppSite
{
    //public enum RefreshMode
    //{
    //    Refreshclient = 0,
    //    NoRefresh = 1,
    //    Refresh = 2
    //}
    public class AppSiteSetting : IEntity<int>
    {
        private const string _format = "{0}:{1}";
        public AppSiteSetting()
        {
        }

        public AppSiteSetting(AppSite appSite)
        {
            this.AppSite = appSite;
        }

        public virtual int ID { get; protected set; }

        public virtual AppSite AppSite { get; protected set; }
        private int AppSiteId { get; set; }


        public virtual bool IsDeleted { get; set; }

        public virtual AppSiteStatus HouseAdStatus
        {
            get;
            set;
        }
        public virtual int TestingModeId
        {
            get;
            set;
        }
        public virtual int RefreshInterval
        {
            get;
            set;
        }
        //public virtual AppSiteRefreshMode RefreshMode
        //{
        //    get;
        //    set;
        //}
        public virtual int RefreshModeId
        {
            get;
            set;
        }
        public virtual bool ChangeHouseAddStatus(AppSiteStatus status)
        {
            throw new System.NotImplementedException();
        }
        public virtual string GetDescription()
        {
            return string.Format("{0}:{1}", AppSite.Name, AppSite.ID);
        }

        public virtual string RefreshModeDescriper(string id)
        {
            RefreshMode Mode = (RefreshMode)Convert.ToInt32(id);
            if (Mode == RefreshMode.Refresh)
            {
                return Framework.Resources.ResourceManager.Instance.GetResource("Refresh", "AppSiteSettings");
            }
            if (Mode == RefreshMode.NoRefresh)
            {
                return Framework.Resources.ResourceManager.Instance.GetResource("NoRefresh", "AppSiteSettings");

            }
            if (Mode == RefreshMode.Refreshclient)
            {
                return Framework.Resources.ResourceManager.Instance.GetResource("Refreshclient", "AppSiteSettings");

            }

            return Framework.Resources.ResourceManager.Instance.GetResource("Setto", "AppSiteSettings");


        }
    }
}

