//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.Campaign.Targeting
{
    public class DemographicTargeting : TargetingBase
    {
        public virtual Demographic Demographic
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            return Demographic.GetDescription();
        }
        //ForAuditTrial
        public virtual Gender Demographic_Gender { get; set; }
        public virtual AgeGroup Demographic_AgeGroup { get; set; }

        public override TargetingBase Copy()
        {
            var cloneObj = new DemographicTargeting()
            {
                Demographic = this.Demographic,
                AdGroup = this.AdGroup,
                Type = this.Type,
                IsDeleted = this.IsDeleted
            };
            return cloneObj;
        }
    }
}

