//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.Campaign.Targeting
{
    public class OperatorTargeting : TargetingBase
    {
        public virtual Operator Operator
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            return Operator.GetDescription();
        }

        public override TargetingBase Copy()
        {
            var cloneObj = new OperatorTargeting()
            {
                Operator = this.Operator,
                AdGroup = this.AdGroup,
                Type = this.Type,
                IsDeleted = this.IsDeleted
            };
            return cloneObj;
        }
       

    }
}

