//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using Noqoush.AdFalcon.Domain.Model.Campaign.Targeting;
using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Objective
{
    //[DataContract]
    //public enum AdActionTypeIds
    //{
    //    [EnumMember]
    //    [System.ComponentModel.Description("Test")]
    //    DownloadiOSUniversalApplication = 2,
    //    [EnumMember]
    //    DownloadiPhoneApplication = 3,
    //    [EnumMember]
    //    DownloadiPadApplication = 4,
    //    [EnumMember]
    //    DownloadAndroidApplication = 5,
    //    [EnumMember]
    //    ClickToMobileWeb = 6,
    //    [EnumMember]
    //    ClickToCall = 7,
    //    [EnumMember]
    //    ClickToLocate = 8,
    //    [EnumMember]
    //    ClickToAudio = 9,
    //    [EnumMember]
    //    ClickToVideo = 10,
    //    [EnumMember]
    //    ClickToCanvas = 11,
    //    [EnumMember]
    //    ClickToSMS = 12,
    //    [EnumMember]
    //    Interstitial = 13,
    //    [EnumMember]
    //    RichMedia = 14,
    //    [EnumMember]
    //    Custom = 15,
    //    [EnumMember]
    //    VideoStreaming = 16,
    //         [EnumMember]
    //    AdTrackingIOS = 17,

    //    [EnumMember]
    //    AdTrackingAndroid = 18,


    //            [EnumMember]
    //    AdTrackingIOSForLead = 19,

    //    [EnumMember]
    //    AdTrackingAndroidForLead = 20,


    //    [EnumMember]
    //    AdTracking = 21,
    //}
    public class AdActionTypeBase : ManagedLookupBase
    {
        public virtual string ViewName { get; set; }
        public virtual IList<AdActionTypeConstraint> Constraints
        {
            get;
            set;
        }
        public virtual TileImage ActionImage
        {
            get;
            set;
        }
        public virtual AdActionValue CreateAdAction()
        {
            throw new System.NotImplementedException();
        }

        public virtual int? ShowInAppId { get; set; }
        public virtual int Code { get; set; }

        public virtual IEnumerable<AdActionCostModelWrapper> AdActionCostModelWrappers { get; set; }
        public virtual IEnumerable<CostModelWrapper> CostModelWrappers { get; set; }

        public virtual IEnumerable<AdActionTypeTrackingEvent> AdActionTrackingEvents { get; set; }

        public virtual IEnumerable<AdType> AdTypes { get; set; }
        public virtual IEnumerable<TargetingBase> CreateTargeting()
        {
            throw new System.NotImplementedException();
        }

    }
}

