//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Noqoush.AdFalcon.Domain.Model.Campaign.Objective
{
    public class AdViewVideo : AdActionValue
    {
        public virtual object VideoURL
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            return VideoURL.ToString();
        }
    }
}

