//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Noqoush.AdFalcon.Domain.Model.Core
{
    public class CreativeUnitFormat 
    {
        public virtual int ID { get; set; }
        public virtual bool IsDeleted { get; set; }
        public virtual string Format { get; set; }
        public virtual CreativeUnit CreativeUnit { get; set; }
        public virtual int MaxSize { get; set; }
    }
}

