//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Noqoush.AdFalcon.Domain.Model.Core
{
    public class Keyword :ManagedLookupBase //LookupBase<Keyword, int>
    {
        public virtual int Usage
        {
            get;
            set;
        }
        public virtual bool  IsHidden
        {
            get;
            set;
        } 
        public virtual string Code
        {
            get;
            set;
        }
    }
}

