//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;

namespace Noqoush.AdFalcon.Domain.Model.Core
{
    public class Language : ManagedLookupBase
    {
        public virtual string Code
        {
            get;
            set;
        }
        public virtual bool ForPortal
        {
            get;
            set;
        }
        public virtual string GetCultureName()
        {
            var result = System.Threading.Thread.CurrentThread.CurrentCulture.Name;
            switch (Code)
            {
                case "ar":
                    {
                        result = "ar-JO";
                        break;
                    }
                case "en":
                    {
                        result = "en-US";
                        break;
                    }
            }
            return result;
        }
        public virtual CultureInfo GetCulture()
        {
            return new CultureInfo(GetCultureName());
        }

    }
}

