//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Noqoush.AdFalcon.Domain.Model.Core
{
    public class Platform : ManagedLookupBase //LookupBase<Platform, int>
    {
        public virtual bool IsVisible { get; set; }
        public virtual IEnumerable<Device> Devices { get; set; }
        public virtual IEnumerable<PlatformVersion> Versions { get; set; }
    }
}

