//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Common.Model.AppSite;
using ArabyAds.AdFalcon.Domain.Common.Model.Core;
using ArabyAds.AdFalcon.Domain.Common.Repositories.Campaign;
using ArabyAds.AdFalcon.Domain.Common.Model.Campaign.Objective;
using System.Collections.Generic;

namespace ArabyAds.AdFalcon.Domain.Common.Model.Campaign
{

    [DataContract()]
    public enum AdTypeIds
    {
        [EnumMember]
        Undefined = 0,
        [EnumMember]
        Banner = 1,
        [EnumMember]
        Text = 2,
        [EnumMember]
        PlainHTML = 3,
        [EnumMember]
        RichMedia = 4,
        [EnumMember]
        NativeAd = 5,
        [EnumMember]
        InStreamVideo = 6,
        [EnumMember]
        TrackingAd = 7,
        [EnumMember]
        VideoEndCard = 8,
    
        [EnumMember]
        Interstitial = 9

    }


    [DataContract(Name = "AdTypeGroup")]
    public enum AdTypeGroup
    {
        [EnumMember]

        Undefined = 0,
        [EnumMember]
        [EnumText("Banner", "PMPDeals")]
        Banner = 1,

        [EnumMember]
        [EnumText("NativeAdName", "NativeAd")]
        Native = 2,

        [EnumMember]
        [EnumText("InstreamVideoName", "InstreamVideo")]
        InStream = 3
    }
   

}
