//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting.Device
{
    public class DeviceCapabilityTargeting : DeviceTargetingBase
    {
        public virtual DeviceCapability Capability { get; set; }
        public virtual bool IsInclude { get; set; }
        public override string GetDescription()
        {
            return Capability.GetDescription();
        }

        public override ITargetingBase Copy()
        {
            var cloneObj = new DeviceCapabilityTargeting()
            {
                Capability = this.Capability,
                IsDeleted = this.IsDeleted,
                IsAll = this.IsAll,
                IsInclude = this.IsInclude,
                DeviceTargeting = this.DeviceTargeting
            };
            return cloneObj;
        }
    }
}

