//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting.Device
{
    public class PlatformTargeting : DeviceTargetingBase
    {
        public virtual Platform Platform { get; set; }

        public virtual string MinimumVersion { get; set; }

        public override  string GetDescription()
        {
            return Platform.GetDescription();
        }
        public override ITargetingBase Copy()
        {
            var cloneObj = new PlatformTargeting()
            {
                Platform = this.Platform,
                IsDeleted = this.IsDeleted,
                IsAll = this.IsAll,
                 MinimumVersion = this.MinimumVersion,
                DeviceTargeting = this.DeviceTargeting
            };
            return cloneObj;
        }
    }

}

