//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.AdFalcon.Domain.Repositories.Campaign;
using Noqoush.Framework.DomainServices;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting
{
    //TODO:OSaleh to change this class name
    public interface ITargetingBase
    {
        AdGroup AdGroup { get; set; }
    }


    public class TargetingBase : IEntity<int>, ITargetingBase
    {
        public static ITargetingBaseRepository _targetingBaseRepository = null;
        public static ITargetingBaseRepository TargetingBaseRepository
        {
            get
            {
                if (_targetingBaseRepository == null)
                {
                    _targetingBaseRepository = Framework.IoC.Instance.Resolve<ITargetingBaseRepository>();
                }
                return _targetingBaseRepository;
            }
        }
        public virtual int ID { get; protected set; }
        public virtual bool IsDeleted { get; set; }
        public virtual AdGroup AdGroup { get; set; }
        public virtual TargetingType Type { get; set; }

        public virtual bool IsMatch(AdRequestTargeting adRequest)
        {
            throw new System.NotImplementedException();
        }

        public virtual string GetDescription()
        {
            return Type.GetDescription();
        }
        public virtual TargetingBase Copy()
        {
            var cloneObj = new TargetingBase()
                               {
                                AdGroup = this.AdGroup,
                                Type = this.Type,
                                IsDeleted = this.IsDeleted
                               };
            return cloneObj;
        }

    }
}

