//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Campaign;
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.Framework.DomainServices;

namespace Noqoush.AdFalcon.Domain.Model.AppSite.Filtering
{
    public class AppSiteFilter : IEntity<int>
    {
        private  bool _IsDeleted;

        public virtual int ID { get; protected set; }
        public virtual bool IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                _IsDeleted = value;
            }
        }
        public virtual AppSite AppSite { get;  set; }

        public virtual bool CIsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                _IsDeleted = value;
            }
        }
        public virtual int CAppSiteId
        {
            get;
            set;
        }


        public virtual bool IsMatch(AdCreative ad)
        {
            throw new System.NotImplementedException();
        }
        public virtual string GetDescription()
        {
            return ToString();
        }
    }
}

