//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Common.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Common.Model.AppSite
{
    [DataContract()]
    public enum AppSiteTypeEnum
    {
        [EnumMember]
        Android = 1,
        [EnumMember]
        iOS = 2,
        [EnumMember]
        MobileWeb = 3
    }

    //public class AppSiteType : LookupBase<AppSiteType, int>
    //{
    //    public virtual string ViewName { get; set; }

    //    public virtual string IconURL
    //    {
    //        get;
    //        set;
    //    }

    //    public virtual bool IsThemeable
    //    {
    //        get;
    //        set;
    //    }

    //    public virtual Platform Platform
    //    {
    //        get;
    //        set;
    //    }

    //    public virtual bool IsApp
    //    {
    //        get;
    //        set;
    //    }

    //}
}

