//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Common.Model.Core;

namespace Noqoush.AdFalcon.Domain.Common.Model.AppSite
{
    //public class MatchType : LookupBase<MatchType, int>
    //{
    //    //Exact,Contains,
    //}
}
