//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.AppSite
{
    public class AppSiteRefreshMode : LookupBase<AppSiteRefreshMode, int>
    {
       // NoRefresh,ClientCode,Custom,
    }
}
