//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WURFLWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WURFLWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;wurfl_patch&gt;
        ///	&lt;version&gt;
        ///		&lt;last_updated&gt;April 8, 2011&lt;/last_updated&gt;
        ///	&lt;/version&gt;
        ///	&lt;devices&gt;
        ///		&lt;!-- Web browsers --&gt;
        ///		&lt;device user_agent=&quot;DO_NOT_MATCH_GENERIC_WEB_BROWSER&quot; fall_back=&quot;generic&quot; id=&quot;generic_web_browser&quot;&gt;
        ///			&lt;group id=&quot;product_info&quot;&gt;
        ///				&lt;capability name=&quot;brand_name&quot; value=&quot;generic web browser&quot;/&gt;
        ///				&lt;capability name=&quot;model_name&quot; value=&quot;&quot;/&gt;
        ///				&lt;capability name=&quot;pointing_method&quot; value=&quot;mouse&quot;/&gt;
        ///				&lt;capability name=&quot;is_wireless_device&quot; value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string web_browsers_patch {
            get {
                return ResourceManager.GetString("web_browsers_patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;wurfl&gt;
        ///  &lt;version&gt;
        ///    &lt;ver&gt;db.scientiamobile.com - 2015-05-03 00:54:40&lt;/ver&gt;
        ///    &lt;last_updated&gt;Sun May 03 00:58:40 -0400 2015&lt;/last_updated&gt;
        ///    &lt;official_url&gt;http://wurfl.sourceforge.net/&lt;/official_url&gt;
        ///	    &lt;maintainers&gt;
        ///	        &lt;maintainer name=&quot;Luca Passani&quot; email=&quot;luca at scientiamobile dot com&quot; home_page=&quot;http://www.scientiamobile.com&quot;/&gt;
        ///	        &lt;maintainer name=&quot;Steve Kamerman&quot; email=&quot;steve at scientiamobile dot com&quot; home_page=&quot;http://www.scientiamobile.com&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wurfl {
            get {
                return ResourceManager.GetString("wurfl", resourceCulture);
            }
        }
    }
}
