//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Common.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Common.Model.Account
{
    public enum FeaturesCode
    {
        PopOver = 1,
    }

    //public class Feature : ManagedLookupBase
    //{
    //    public virtual FeaturesCode Code { set; get; }
    //}
}

