//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using Noqoush.AdFalcon.Domain.Model.AppSite;
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.AdFalcon.Domain.Repositories.Campaign;
using Noqoush.AdFalcon.Domain.Model.Campaign.Objective;
using System.Collections.Generic;
using Noqoush.Framework.DomainServices;
using Noqoush.AdFalcon.Domain.Common.Model.Campaign;

namespace Noqoush.AdFalcon.Domain.Model.Campaign
{

    //[DataContract()]
    //public enum AdTypeIds
    //{
    //    [EnumMember]
    //    Undefined = 0,
    //    [EnumMember]
    //    Banner = 1,
    //    [EnumMember]
    //    Text = 2,
    //    [EnumMember]
    //    PlainHTML = 3,
    //    [EnumMember]
    //    RichMedia = 4,
    //    [EnumMember]
    //    NativeAd = 5,
    //    [EnumMember]
    //    InStreamVideo = 6,
    //    [EnumMember]
    //    TrackingAd = 7,
    //    [EnumMember]
    //    VideoEndCard = 8
    //}


    //[DataContract(Name = "AdTypeGroup")]
    //public enum AdTypeGroup
    //{
    //    [EnumMember]

    //    Undefined = 0,
    //    [EnumMember]
    //    [EnumText("Banner", "PMPDeals")]
    //    Banner = 1,

    //    [EnumMember]
    //    [EnumText("NativeAdName", "NativeAd")]
    //    Native = 2,

    //    [EnumMember]
    //    [EnumText("InstreamVideoName", "InstreamVideo")]
    //    InStream = 3
    //}
    public class AdType : LookupBase<AdType, int>
    {
        private static IAdTypeRepository _adTypeRepository = null;
        public virtual IEnumerable<AdActionTypeBase> AdActions { get; set; }
        static AdType _banner = null;
        static AdType _text = null;
        static AdType _html = null;
        static AdType _richMedia = null;
        static readonly object LockObj = new object();

        private static IAdTypeRepository ATypeRepository
        {
            get { return _adTypeRepository ?? (_adTypeRepository = Framework.IoC.Instance.Resolve<IAdTypeRepository>()); }
        }
        public virtual IEnumerable<AdSubType> SubTypes { get; set; }
        public virtual PortalPermision Permission { get; set; }

        public virtual AdTypeGroup Group { get; set; }
        public static AdType Banner
        {
            get
            {
                if (_banner == null)
                {
                    lock (LockObj)
                    {
                        if (_banner == null)
                        {
                            _banner = ATypeRepository.Get((int)AdTypeIds.Banner);
                        }
                    }
                }
                return _banner;
            }
        }

        public static AdType Text
        {
            get
            {
                if (_text == null)
                {
                    lock (LockObj)
                    {
                        if (_text == null)
                        {
                            _text = ATypeRepository.Get((int)AdTypeIds.Text);
                        }
                    }
                }
                return _text;
            }
        }

        public static AdType PlainHTML
        {
            get
            {
                if (_html == null)
                {
                    lock (LockObj)
                    {
                        if (_html == null)
                        {
                            _html = ATypeRepository.Get((int)AdTypeIds.PlainHTML);
                        }
                    }
                }
                return _html;
            }
        }

        public static AdType RichMedia
        {
            get
            {
                if (_richMedia == null)
                {
                    lock (LockObj)
                    {
                        if (_richMedia == null)
                        {
                            _richMedia = ATypeRepository.Get((int)AdTypeIds.RichMedia);
                        }
                    }
                }
                return _richMedia;
            }
        }
    }

}
