//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign
{
    public class CreativeVendor : ManagedLookupBase
    {
        public virtual IList<CreativeVendorKeyword> Keywords { get; set; }
        public virtual int Code { get; set; }
    } }
//CreativeVendorKeyword