//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ArabyAds.AdFalcon.Domain.Model.AppSite;
using ArabyAds.AdFalcon.Domain.Model.AppSite.Filtering;
using ArabyAds.AdFalcon.Domain.Model.Campaign;
using ArabyAds.AdFalcon.Domain.Model.Core;
using ArabyAds.Framework.DomainServices;

public class AppSiteFilterSet : IEntity<int>, IList<AppSiteFilter>
{
    public virtual int ID { get; protected set; }
    public virtual bool IsDeleted { get; set; }

    public virtual AppSite AppSite { get; set; }

    private List<AppSiteFilter> filters;

    public AppSiteFilterSet()
    {
        filters = new List<AppSiteFilter>();
    }

    public virtual bool IsMatch(AdCreative ad)
    {
        throw new NotImplementedException();
    }


    public int IndexOf(AppSiteFilter item)
    {
        return filters.IndexOf(item);
    }

    public void Insert(int index, AppSiteFilter item)
    {
        filters.Insert(index, item);
    }

    public void RemoveAt(int index)
    {
        filters.RemoveAt(index);
    }

    public AppSiteFilter this[int index]
    {
        get { return filters[index]; }
        set { filters[index] = value; }
    }

    public void Add(AppSiteFilter item)
    {
        filters.Add(item);
    }

    public void Clear()
    {
        filters.Clear();
    }

    public bool Contains(AppSiteFilter item)
    {
        return filters.Contains(item);
    }

    public void CopyTo(AppSiteFilter[] array, int arrayIndex)
    {
        filters.CopyTo(array, arrayIndex);
    }

    public int Count
    {
        get { return filters.Count; }
    }

    public bool IsReadOnly
    {
        get { return true; }
    }

    public bool Remove(AppSiteFilter item)
    {
        return filters.Remove(item);
    }

    public IEnumerator<AppSiteFilter> GetEnumerator()
    {
        return filters.GetEnumerator();
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return filters.GetEnumerator();
    }
    public virtual string GetDescription()
    {
        return ToString();
    }
}

