//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Campaign;
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.AppSite.Filtering
{
    public class KeywordsFilter : AppSiteFilter
    {
        public virtual Keyword Keyword
        {
            get;
            set;
    
    }
        public override string GetDescription()
        {
            return Keyword.GetDescription();
        }
        public virtual bool IsMatch(AdCreative ad)
        {
            throw new System.NotImplementedException();
        }

    }
}

