//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Campaign;

namespace ArabyAds.AdFalcon.Domain.Model.AppSite.Filtering
{
    public class TextFilter : AppSiteFilter
    {
        public virtual MatchType MatchType
        {
            get;
            set;
        }

        public virtual string Text
        {
            get;
            set;
        }

        public override string GetDescription()
        {
            return MatchType.GetDescription();
        }
        public virtual bool IsMatch(AdCreative ad)
        {
            throw new System.NotImplementedException();
        }

    }
}

