//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Campaign;
using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.AppSite.Filtering
{
    public class LanguageFilter : AppSiteFilter
    {
        public virtual Language Language
        {
            get;
            set;
        }

        public override string GetDescription()
        {
            return Language.GetDescription();
        }
        public virtual bool IsMatch(AdCreative ad)
        {
            throw new System.NotImplementedException();
        }

    }
}

