//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Campaign;

namespace Noqoush.AdFalcon.Domain.Model.AppSite.Filtering
{
    public class UrlFilter : AppSiteFilter
    {
        public virtual string URL
        {
            get;
            set;
        }


        public override string GetDescription()
        {
            return URL;
        }
        public virtual bool IsMatch(AdCreative ad)
        {
            throw new System.NotImplementedException();
        }
    }
}

