//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting.Device
{
    public class ManufacturerTargeting : DeviceTargetingBase
    {
        public virtual Manufacturer Manufacturer { get; set; }

        public override  string GetDescription()
        {
            return Manufacturer.GetDescription();
        }

        public override ITargetingBase Copy()
        {
            var cloneObj = new ManufacturerTargeting()
            {
                Manufacturer = this.Manufacturer,
                IsDeleted = this.IsDeleted,
                IsAll = this.IsAll,
                DeviceTargeting = this.DeviceTargeting
            };
            return cloneObj;
        }
    }
}

