//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.Framework.DomainServices;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting.Device
{
    public class ModelTargeting : DeviceTargetingBase
    {
        public virtual Model.Core.Device Device { get; set; }
        public override  string GetDescription()
        {
            return Device.GetDescription();
        }
        public override ITargetingBase Copy()
        {
            var cloneObj = new ModelTargeting()
            {
                Device = this.Device,
                IsDeleted = this.IsDeleted,
                IsAll = this.IsAll,
                DeviceTargeting = this.DeviceTargeting
            };
            return cloneObj;
        }
    }
}

