//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.Framework.DomainServices;
using System.Collections.Generic;
using System.Linq;

namespace Noqoush.AdFalcon.Domain.Model.Campaign
{
    public class AdCreativeUnitVendor : IEntity<int>
    {
        public AdCreativeUnitVendor()
        {

        }
        public virtual int ID { get;  set; }
        public virtual bool IsDeleted { get; set; }
        public virtual AdCreativeUnit Unit { get; set; }
        public virtual CreativeVendor Vendor { get; set; }

        public virtual string GetDescription()
        {
            return Vendor.GetDescription();
        }
    } }