//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Noqoush.AdFalcon.Domain.Common.Model.Campaign
{
    [DataContract(Name = "TargetingConnectionType")]
    public enum TargetingConnectionType
    {
        [EnumMember]
         [EnumText("Wifi", "Campaign")]
        WIFI = 1,
  
      
        [EnumMember]
        [EnumText("Cellular", "Campaign")]
        Cellular = 2,
        
     
    }

    [DataContract(Name = "BiddingStrategy")]
    public enum BiddingStrategy
    {
        [EnumMember]
        Unknown =0,
        [EnumMember]
        [EnumText("FixedType", "Lookup")]
        Fixed = 1,


        [EnumMember]
        [EnumText("Dynamic", "Global")]
        Dynamic = 2,


    }

    [DataContract(Name = "ConversionSetting")]
    public enum ConversionSetting
    {
        [EnumMember]
        Unknown = 0,
        [EnumMember]
        [EnumText("FixedType", "Lookup")]
        CountingFirst = 1,


        [EnumMember]
        [EnumText("Dynamic", "Global")]
        CountingEvery = 2,
        [EnumMember]
        [EnumText("Dynamic", "Global")]
        CountingAll = 3,

    }

    [DataContract(Name = "ConversionType")]
    public enum ConversionType
    {
        [EnumMember]
        Unknown = 0,
        [EnumMember]
        [EnumText("Click", "Global")]
        Click = 1,


        [EnumMember]
        [EnumText("ViewAndClick", "Commands")]
        ClickView = 2,


    }
    [DataContract()]
    public enum AdPositionEnum
    {  
        [EnumMember]
        Undefined = 0,
        [EnumMember]
        AboveTheFold = 1,
        [EnumMember]
        BelowTheFold = 2,

        [EnumMember]
        Unknown = 4,

    }


    [DataContract(Name = "CountingTypeAttribuation")]
    public enum CountingTypeAttribuation
    {
        [EnumMember]
        Unknown = 0,
        [EnumMember]
        [EnumText("Minutes", "Time" )]
        Minutes = 1,


        [EnumMember]
        [EnumText("Hours", "Time")]
        Hours = 2,
        [EnumMember]
        [EnumText("Days", "Time")]
        Days = 3,
        [EnumMember]
        [EnumText( "Months", "Time")]
        Months = 4,

    }


  


}

