//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Noqoush.AdFalcon.Domain.Common.Model.Core;

namespace Noqoush.AdFalcon.Domain.Common.Model.Campaign
{
    //public class CreativeFormat : ManagedLookupBase
    //{
    //    public virtual string Code { set; get; }
    //    public virtual string Description { set; get; }
    //}
}
