//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Account;
using ArabyAds.Framework.DomainServices;
using System;

namespace ArabyAds.AdFalcon.Domain.Model.Account
{
    public class AccountFeatures
    {
        public virtual DateTime DateNotify { get; set; }
        public virtual int ID { get; set; }
        public virtual Feature Feature { get; set; }
        public virtual User User { get; set; }

        public virtual Account Account { get; set; }


    }
}

