//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.AdFalcon.Domain.Model.Core;

namespace ArabyAds.AdFalcon.Domain.Model.Account
{
    public class  FundType : LookupBase<FundType,int>
    {
        public virtual bool AllowImpersonate
        {
            get;
            set;
        }
    }
}

