//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using ArabyAds.Framework.DomainServices;

namespace ArabyAds.AdFalcon.Domain.Model.Account
{
    public class Transfer : IEntity<int>
    {
        private const string _format = "{0}";
        public virtual bool IsDeleted { get; set; }
        public virtual Account Account
        {
            get;
            set;
        }

        public virtual DateTime TransferDate
        {
            get;
            set;
        }

        public virtual float Amount
        {
            get;
            set;
        }

        public virtual string GetDescription()
        {
            return string.Format(_format, Amount.ToString("F2"));
        }
        public virtual int ID { get; protected set; }
        //public virtual string GetDescription()
        //{
        //    return ToString();
        //}
    }
}

