//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Noqoush.AdFalcon.Domain.Common.Model.Core
{
    //public class Device : ManagedLookupBase//LookupBase<Device, int>
    //{
    //    public virtual DeviceType DeviceType{get;set;}
    //    public virtual Manufacturer Manufacturer{get;set;}
    //    public virtual Platform Platform{get;set;}
    //    public virtual string Code { get; set; }
    //}
}

