//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Noqoush.AdFalcon.Domain.Common.Model.Core
{
    //public class Gender:LookupBase<Gender,int>
    //{
    //    /*Male,
    //    Female,
    //    NA,*/
    //}
}
