//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    public class AgeGroup : ManagedLookupBase
    {
        public virtual int MinValue { get; set; }
        public virtual int MaxValue { get; set; }

    }
}
