//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Common.Model.Campaign;
using ArabyAds.AdFalcon.Domain.Model.Campaign;
using ArabyAds.Framework.DomainServices;

namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    //[DataContract()]
    //public enum RequiredType
    //{
    //    [EnumMember]
    //    [EnumText("Optional", "Global")]
    //    Optional = 1,
    //    [EnumMember]
    //    [EnumText("Required", "Global")]
    //    Required = 2,
    //    [EnumMember]
    //    [EnumText("PartialRequired", "Global")]
    //    PartialRequired = 3
    //}
    public class CreativeUnit : LookupBase<CreativeUnit, int>
    {
        public virtual string Description { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual IList<CreativeUnitFormat> Formats { get; set; }
        public virtual OrientationType OrientationType { get; set; }
        public virtual int Width { get; set; }
        public virtual int Height { get; set; } 
        public virtual int HD_Width { get; set; }
        public virtual int HD_Height { get; set; }
        public virtual int PreviewWidth { get; set; }
        public virtual int PreviewHeight { get; set; }
        public virtual IList<CreativeUnitGroup> Groups { get; set; }
        public virtual IList<AdSupportedCreativeUnit> SupportedTypes { get; set; }
        public virtual string Code { get; set; }
        public override string ToString()
        {
            return string.Format("{0}X{1}", Width, Height);
        }
    }
}

