//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ArabyAds.Framework.DomainServices;
using System.Collections.Generic;

namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    public class Device : ManagedLookupBase//LookupBase<Device, int>
    {
        public virtual DeviceType DeviceType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual string Code { get; set; }
        public virtual IList<DeviceCode> Codes { get; set; }

    }

    public class DeviceCode: IEntity<int>
        {
        public virtual int ID { get; set; }
        public virtual Device Device { get; set; }
        public virtual string Code { get; set; }
        public virtual bool IsDeleted { get; set; }
        public virtual void Delete()
        {
            IsDeleted = true;
        }

        public virtual string GetDescription()
        {
            return Code;
        }


    }
}

