//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    public class Gender:LookupBase<Gender,int>
    {
        /*Male,
        Female,
        NA,*/
    }
}
