//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    public class State : Location<State, Country, City>
    {
    }
}

