//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ArabyAds.AdFalcon.Domain.Model.Campaign;

namespace ArabyAds.AdFalcon.Domain.Model.Core
{
    public class TileImageFormat
    {
        public virtual int ID { get; set; }
        public virtual bool IsDeleted { get; set; }
        public virtual string Format { get; set; }
        public virtual TileImageSize TileImageSize { get; set; }
        public virtual int MaxSize { get; set; }
    }
}

