//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Noqoush.AdFalcon.Domain.Model.Core;
using Noqoush.Framework.DomainServices;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting
{
    public class Demographic:IComplexEntity
    {
        public virtual bool IsDeleted { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual AgeGroup AgeGroup { get; set; }

        public virtual string GetDescription()
        {
            return string.Format(Framework.Resources.ResourceManager.Instance.GetResource("Gender", "Global")  + ":{0}," + Framework.Resources.ResourceManager.Instance.GetResource("AgeGroup", "Global")  + ":{1}", Gender!=null ? Gender.GetDescription():Framework.Resources.ResourceManager.Instance.GetResource("both", "Global"), AgeGroup!=null?AgeGroup.GetDescription():Framework.Resources.ResourceManager.Instance.GetResource("All", "Global")); //Gender, AgeGroup);//
        }
    }
}

