//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Noqoush.AdFalcon.Domain.Model.Core;

namespace Noqoush.AdFalcon.Domain.Model.Campaign.Targeting
{
    public class GeographicTargeting : TargetingBase
    {
        public virtual LocationBase Location
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            return Location.GetDescription();
        }
        public override TargetingBase Copy()
        {
            var cloneObj = new GeographicTargeting()
            {
                Location = this.Location,
                AdGroup = this.AdGroup,
                Type = this.Type,
                IsDeleted = this.IsDeleted
            };
            return cloneObj;
        }
    }
}

