//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Runtime.Serialization;
using ArabyAds.AdFalcon.Domain.Common.Model.Campaign;


namespace ArabyAds.AdFalcon.Domain.Common.Model.Core
{
    [DataContract()]
    public enum RequiredType
    {
        [EnumMember]
        [EnumText("Optional", "Global")]
        Optional = 1,
        [EnumMember]
        [EnumText("Required", "Global")]
        Required = 2,
        [EnumMember]
        [EnumText("PartialRequired", "Global")]
        PartialRequired = 3
    }
   
}

