//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace ArabyAds.AdFalcon.Domain.Common.Model.Core
{
    [DataContract()]
    public enum DeviceTypeEnum
    {
        [EnumMember]
        Any = 0,
        [EnumMember]
        SmartPhone = 1,
        [EnumMember]
        Tablet = 2
    }
    //public class DeviceType : ManagedLookupBase
    //{

    //}
}

