//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Noqoush.AdFalcon.Domain.Common.Model.Core
{//{
//    public class DocumentType : LookupBase<DocumentType, int>
//    {
//        public virtual string Code { get; set; }
//        public virtual IList<MIMEType> MIMETypes { get; set; }
//    }
}

