//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;


namespace ArabyAds.AdFalcon.Domain.Common.Model.Core
{
    [DataContract()]
    public enum LanguageType
    {
        [EnumMember]
       
        ar = 1,
        [EnumMember]
       
        en = 2,

    }
    /*public class Party : IEntity<int>
    {
        public virtual int ID { get; set; }

        public virtual string Name { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool IsDeleted { get; set; }
        public virtual bool IsValid { get; set; }
        public virtual string GetDescription()
        {
            return Name;
        }
        public override string ToString()
        {
            return this.Name;
        }
        public virtual void Validate()
        {
            IsValid = false;
            //create business Exception to hold error data list 
            var error = new BusinessException();
            //validate Name
            if (string.IsNullOrWhiteSpace(Name))
            {
                error.Errors.Add(new ErrorData { ID = "PartyNameBR" });
            }
            if (error.Errors.Count > 0)
            {
                IsValid = false;
                throw (error);
            }
            IsValid = DataAnnotationsValidator.TryValidate(this);
            IsValid = true;
        }
        public virtual string TypeNameString { get; set; }
    }*/
}
