//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ArabyAds.AdFalcon.Domain.Model.Campaign.Objective
{
    public class AdCall : AdActionValue
    {
        public virtual string PhoneNumber
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            return PhoneNumber;
        }
    }
}

