//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ArabyAds.AdFalcon.Domain.Model.Campaign.Objective
{
    public class Adlocate : AdActionValue
    {
        public virtual IEnumerable<string> Keywords
        {
            get;
            set;
        }
        public override string GetDescription()
        {
            string result = string.Empty;
            foreach (var item in Keywords) {

                result = item + ","  ;
                    
            }
            return result;
        }
    }
}

